# Generated by Django 4.2.17 on 2026-02-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventory", "0028_client_country_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="legacy_client_name",
            field=models.CharField(
                blank=True,
                help_text="Legacy client name from old database",
                max_length=200,
                null=True,
            ),
        ),
    ]
